### ISSUE TITLE
Choice Prize

### ISSUE THREAD

**Issue by Bhaney44** [ChoiceCoin/Quantum#4]
# Choice Prize

**Reward**. 
1,000,000 Choice for the first complete refute of my [Proof of the Birch Swinnerton Dyer Conjecture](https://deliverypdf.ssrn.com/delivery.php?ID=984094084082030117102003127122092068102080021061010049073015110118078002022116110098016059027059030017044101098119004085114023043027046041038066114104117112090092024095049046113106088071094022031098112030092077068026124103117006075091101101101081123007&EXT=pdf&INDEX=TRUE).

**Rules**.
1. No human can do it.
2. No machine can do it.
3. Breaking the rules is allowed.

**Deadline**.
No deadline. 

**Submission**. 
By PR on the Choice Coin Quantum GitHub in the [BSD](https://github.com/ChoiceCoin/Quantum/tree/main/BSD) folder.

**Comment by ChoiceCoin** [comment]
Congrats to @paradd0x1 for winning the Choice Prize for his refute using chatGPT. [Refute](https://github.com/ChoiceCoin/Quantum/blob/main/BSD/ChatGPT%20response%20to%20the%20given%20proof%20of%20the%20Birch%20Swinnerton%20Dyer%20Conjecture.pdf).
